spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management_system
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:      ddl-auto: update
    show-sql: true

#logging:#  level:
#    root: debug 

server:  compression:    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg  