spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/employee_managment_system
    username: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
